from abc import ABC, abstractmethod

from domain.shared.ports.repository import IBaseRepository


class StockItemRepository(IBaseRepository, ABC): ...

class StockCategoryRepository(IBaseRepository, ABC): ...

class HazardRepository(IBaseRepository, ABC): ...

class StockUnitRepository(IBaseRepository, ABC): ...

class StockPackagingRepository(IBaseRepository, ABC): ...

class StockProductRepository(IBaseRepository, ABC): ...

class StockOrderProductRepository(IBaseRepository, ABC): ...

class StockTransactionRepository(IBaseRepository, ABC):  ...

class StockAdjustmentRepository(IBaseRepository, ABC): ...

class StockOrderRepository(IBaseRepository, ABC): ...