"""init

Revision ID: 8007c8a98e07
Revises: 23d73921be57
Create Date: 2023-08-26 11:19:07.356151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8007c8a98e07'
down_revision = '23d73921be57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
