<script setup lang="ts">
import { reactive, onMounted, ref } from "vue";
import { REST_BASE_URL } from "@/conf";
import { useAnalysisStore } from "@/stores/analysis";
import { ReportListingType } from "@/types/reports";
import useAnalyticsComposable from "@/composables/analytics";
import { formatDate } from "@/utils";

const analysisStore = useAnalysisStore();
const { reports, fetchReports, generateReport, deleteReport } = useAnalyticsComposable();
const isLoading = ref(false);
const showForm = ref(false)

const state = reactive({
  listingForm: {
    report_type: "",
    analyses_uids: [],
    sample_states: [],
    date_column: "",
    period_start: "",
    period_end: "",
  } as ReportListingType,
});

onMounted(async () => {
  isLoading.value = true;
  analysisStore.fetchAnalysesServices({
    first: undefined,
    after: "",
    text: "",
    sortBy: ["name"],
  });
  await fetchReports().finally(() => {
    isLoading.value = false;
  });
});

const saveListingForm = () => {
  generateReport({ ...state.listingForm });
  showForm.value = false;
};

const downloadReport = (report: any) => {
  const link = document.createElement("a");
  link.download = report.report_type + "-" + report.crated_at;
  link.href = REST_BASE_URL + "/" + report.location;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
</script>

<template>
  <div class="mt-4">
    <div class="flex justify-between items-center mb-4">
      <h1 class="text-xl text-foreground font-semibold">Line Listing Reports</h1>
      <button
        class="bg-primary text-primary-foreground px-4 py-2 rounded-md hover:bg-primary/90"
        @click="showForm = true"
      >
        Generate Report
      </button>
    </div>

    <div v-if="isLoading" class="text-center py-4">
      <fel-loader message="Loading reports..." />
    </div>

    <div v-else-if="!reports?.length" class="text-center py-4 text-muted-foreground">
      <p class="text-destructive">There are no downloaded reports yet</p>
      <hr class="my-2" />
      <p class="italic">
        Once a download request has been made, your reports will appear here
      </p>
    </div>

    <div v-else class="overflow-x-auto">
      <table class="min-w-full bg-background shadow rounded-sm border border-foreground">
        <thead>
          <tr>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              <input type="checkbox" />
            </th>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              Report Type
            </th>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              Generated By
            </th>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              Date Generated
            </th>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              Period Start
            </th>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              Period End
            </th>
            <th class="px-4 py-2 border-b border-foreground text-left text-foreground">
              Status
            </th>
            <th class="px-4 py-2 border-b border-foreground"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="report in reports" :key="report.uid" class="hover:bg-accent/50">
            <td class="px-4 py-2 border-b border-foreground">
              <input type="checkbox" />
            </td>
            <td class="px-4 py-2 border-b border-foreground text-primary">
              {{ report.report_type }}
            </td>
            <td class="px-4 py-2 border-b border-foreground text-primary">
              {{ report?.created_by?.first_name }}
              {{ report?.created_by?.last_name }}
            </td>
            <td class="px-4 py-2 border-b border-foreground text-primary">
              {{ formatDate(report?.created_at, 'YYYY-MM-DD HH:mm') }}
            </td>
            <td class="px-4 py-2 border-b border-foreground text-primary">
              {{ formatDate(report?.period_start, 'YYYY-MM-DD HH:mm') }}
            </td>
            <td class="px-4 py-2 border-b border-foreground text-primary">
              {{ formatDate(report?.period_end, 'YYYY-MM-DD HH:mm') }}
            </td>
            <td class="px-4 py-2 border-b border-foreground">
              <span
                :class="{
                  'bg-success/10 text-success': report?.status?.toLocaleLowerCase() === 'ready',
                  'bg-warning/10 text-warning': report?.status?.toLocaleLowerCase() === 'processing',
                  'bg-destructive/10 text-destructive': report?.status?.toLocaleLowerCase() === 'failed',
                }"
                class="px-2 py-1 rounded-full text-sm"
              >
                {{ report?.status }}
              </span>
            </td>
            <td class="px-4 py-2 border-b border-foreground text-right space-x-2">
              <button
                v-if="report.status?.toLowerCase() === 'ready'"
                class="px-3 py-1 border border-primary text-primary rounded-md hover:bg-primary hover:text-primary-foreground"
                @click="downloadReport(report)"
              >
                Download
              </button>
              <button
                v-if="['ready', 'failed', 'pending'].includes(report.status?.toLowerCase() ?? '')"
                class="px-3 py-1 border border-destructive text-destructive rounded-md hover:bg-destructive hover:text-destructive-foreground"
                @click="deleteReport(report)"
              >
                Delete
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <fel-modal v-if="showForm" @close="showForm = false" :content-width="'w-3/4'">
      <template v-slot:header>
        <h3 class="text-lg font-semibold text-foreground">Generate Line Listing Report</h3>
      </template>
      <template v-slot:body>
        <form @submit.prevent="saveListingForm" class="space-y-4">
          <div class="grid grid-cols-3 gap-4">
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">Report Type</label>
              <select
                v-model="state.listingForm.report_type"
                class="w-full px-3 py-2 border border-input rounded-md"
              >
                <option value="line_listing">Line Listing</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">Analyses</label>
              <select
                v-model="state.listingForm.analyses_uids"
                class="w-full px-3 py-2 border border-input rounded-md"
                multiple
              >
                <option
                  v-for="service in analysisStore.analysesServices"
                  :key="service.uid"
                  :value="service.uid"
                >
                  {{ service.name }}
                </option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">States</label>
              <select
                v-model="state.listingForm.sample_states"
                class="w-full px-3 py-2 border border-input rounded-md"
                multiple
              >
                <option value="published">Published</option>
                <option value="verified">Verified</option>
                <option value="to_be_verified">To Be Verified</option>
                <option value="received">Received</option>
                <option value="cancelled">Cancelled</option>
                <option value="rejected">Rejected</option>
                <option value="invalidated">Invalidated</option>
                <option value="due">Due</option>
              </select>
            </div>
          </div>

          <div class="grid grid-cols-3 gap-4">
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">Period Date Criteria</label>
              <select
                v-model="state.listingForm.date_column"
                class="w-full px-3 py-2 border border-input rounded-md"
              >
                <option value="created_at">Created Date</option>
                <option value="date_published">Published Date</option>
                <option value="date_submitted">Submission Date</option>
                <option value="date_verified">Verified Date</option>
                <option value="date_cancelled">Cancellation Date</option>
                <option value="date_invalidated">Invalidation Date</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">Period Start</label>
              <input
                v-model="state.listingForm.period_start"
                type="datetime-local"
                class="w-full px-3 py-2 border border-input rounded-md"
                required
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">Period End</label>
              <input
                v-model="state.listingForm.period_end"
                type="datetime-local"
                class="w-full px-3 py-2 border border-input rounded-md"
                required
              />
            </div>
          </div>

          <div class="flex justify-end space-x-2">
            <button
              type="button"
              class="px-4 py-2 border border-input rounded-md hover:bg-accent"
              @click="showForm = false"
            >
              Cancel
            </button>
            <button
              type="submit"
              class="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90"
              :disabled="isLoading"
            >
              Generate
            </button>
          </div>
        </form>
      </template>
    </fel-modal>
  </div>
</template>
