mutation CreateAll {
  createUser(email: "aurtur@study.inc", firstname: "one", lastname: "two", token: "") {
    user {
      firstName
      lastName
      email
      uid
    }
  }
  createUserAuth(userUid: 1, token: "", username: "ceam2", password: "password1", passwordc: "password1") {
    userAuth {
      uid
      userName
      uid
      loginRetry
      lcuser {
        firstName
        lastName
        labManager {
          edges {
            node {
              labName
              email
            }
          }
        }
      }
    }
  }
  ulinkUserAuth(userUid: 0, token: "") {
    user {
      uid
      firstName
      lastName
      email
      auth {
        userName
        uid
      }
    }
  }
}

query LabAndUser {
  userByEmail(email: "admin@stanchionlabs.inc") {
    email
    firstName
    lastName
    uid
  }
  userAll {
    edges {
      node {
        lastName
        firstName
        uid
        isActive
        isSuperuser
        email
        mobilePhone
        businessPhone
        authUid
        auth {
          userName
        }
      }
    }
  }
}
