"""added jobs tables

Revision ID: 62c9ae0d42b7
Revises: 8007c8a98e07
Create Date: 2023-08-26 11:21:27.534832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62c9ae0d42b7'
down_revision = '8007c8a98e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('creator_uid', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('next_try', sa.DateTime(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_job_uid'), 'job', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_uid'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
