"""subclassed Message to MPTT to allow for replies

Revision ID: 0c406729a002
Revises: bb0846d0b978
Create Date: 2021-12-05 09:11:53.286564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0c406729a002'
down_revision = 'bb0846d0b978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thread_uuid', sa.String(), nullable=False))
    op.add_column('message', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('rgt', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('level', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_message_level'), 'message', ['level'], unique=False)
    op.create_index(op.f('ix_message_lft'), 'message', ['lft'], unique=False)
    op.create_index(op.f('ix_message_rgt'), 'message', ['rgt'], unique=False)
    op.create_foreign_key(None, 'message', 'message', ['parent_id'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_rgt'), table_name='message')
    op.drop_index(op.f('ix_message_lft'), table_name='message')
    op.drop_index(op.f('ix_message_level'), table_name='message')
    op.drop_column('message', 'level')
    op.drop_column('message', 'rgt')
    op.drop_column('message', 'lft')
    op.drop_column('message', 'parent_id')
    op.drop_column('message', 'tree_id')
    op.drop_column('message', 'thread_uuid')
    # ### end Alembic commands ###
