"""added date published

Revision ID: 17e9b06ef7d3
Revises: 1caac8f101da
Create Date: 2021-11-27 21:46:42.305620

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '17e9b06ef7d3'
down_revision = '1caac8f101da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('published_by_uid', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'sample', 'user', ['published_by_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'date_published')
    op.drop_column('sample', 'published_by_uid')
    # ### end Alembic commands ###
