"""added stream object type

Revision ID: 1966565edd0d
Revises: 4591b2fe7b16
Create Date: 2021-12-12 09:46:45.920895

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1966565edd0d'
down_revision = '4591b2fe7b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitystream', sa.Column('action_object_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitystream', 'action_object_type')
    # ### end Alembic commands ###
