"""added auit logs for patient table

Revision ID: 1caac8f101da
Revises: e15adddb70ee
Create Date: 2021-11-07 17:30:13.466295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1caac8f101da'
down_revision = 'e15adddb70ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('created_by_uid', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('updated_by_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient', 'user', ['created_by_uid'], ['uid'])
    op.create_foreign_key(None, 'patient', 'user', ['updated_by_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'updated_by_uid')
    op.drop_column('patient', 'created_by_uid')
    # ### end Alembic commands ###
