"""trian

Revision ID: 2267e38ed38f
Revises: 1966565edd0d
Create Date: 2021-12-16 14:05:16.458627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2267e38ed38f'
down_revision = '1966565edd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
