"""hey

Revision ID: 3af263066ae3
Revises: a2aa2aece98e
Create Date: 2021-09-19 16:46:08.701592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3af263066ae3'
down_revision = 'a2aa2aece98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
