"""ressetingevent hook

Revision ID: 4591b2fe7b16
Revises: 4fca5c08910e
Create Date: 2021-12-12 07:57:08.313679

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4591b2fe7b16'
down_revision = '4fca5c08910e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
