"""rewired event hooked

Revision ID: 4fca5c08910e
Revises: e56fdee8f28e
Create Date: 2021-12-12 07:48:26.810721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4fca5c08910e'
down_revision = 'e56fdee8f28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
