"""refactored ws and wst to accept a single analysis and no more profiles

Revision ID: 7373cfc281a5
Revises: 9b3d6e9ba0e7
Create Date: 2022-03-19 08:03:04.371086

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7373cfc281a5'
down_revision = '9b3d6e9ba0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksheet_profile')
    op.drop_table('worksheet_template_profile')
    op.drop_table('worksheet_analysis')
    op.drop_table('worksheet_template_analysis')
    op.add_column('worksheet', sa.Column('analysis_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'worksheet', 'analysis', ['analysis_uid'], ['uid'])
    op.add_column('worksheettemplate', sa.Column('analysis_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'worksheettemplate', 'analysis', ['analysis_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worksheettemplate', type_='foreignkey')
    op.drop_column('worksheettemplate', 'analysis_uid')
    op.drop_constraint(None, 'worksheet', type_='foreignkey')
    op.drop_column('worksheet', 'analysis_uid')
    op.create_table('worksheet_template_analysis',
    sa.Column('ws_template_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analysis_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], name='worksheet_template_analysis_analysis_uid_fkey'),
    sa.ForeignKeyConstraint(['ws_template_uid'], ['worksheettemplate.uid'], name='worksheet_template_analysis_ws_template_uid_fkey'),
    sa.PrimaryKeyConstraint('ws_template_uid', 'analysis_uid', name='worksheet_template_analysis_pkey')
    )
    op.create_table('worksheet_analysis',
    sa.Column('worksheet_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analysis_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], name='worksheet_analysis_analysis_uid_fkey'),
    sa.ForeignKeyConstraint(['worksheet_uid'], ['worksheet.uid'], name='worksheet_analysis_worksheet_uid_fkey'),
    sa.PrimaryKeyConstraint('worksheet_uid', 'analysis_uid', name='worksheet_analysis_pkey')
    )
    op.create_table('worksheet_template_profile',
    sa.Column('ws_template_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], name='worksheet_template_profile_profile_uid_fkey'),
    sa.ForeignKeyConstraint(['ws_template_uid'], ['worksheettemplate.uid'], name='worksheet_template_profile_ws_template_uid_fkey'),
    sa.PrimaryKeyConstraint('ws_template_uid', 'profile_uid', name='worksheet_template_profile_pkey')
    )
    op.create_table('worksheet_profile',
    sa.Column('worksheet_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], name='worksheet_profile_profile_uid_fkey'),
    sa.ForeignKeyConstraint(['worksheet_uid'], ['worksheet.uid'], name='worksheet_profile_worksheet_uid_fkey'),
    sa.PrimaryKeyConstraint('worksheet_uid', 'profile_uid', name='worksheet_profile_pkey')
    )
    # ### end Alembic commands ###
