"""added adress

Revision ID: 88261aa91d10
Revises: e9da14f42615
Create Date: 2022-03-01 18:18:01.756514

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '88261aa91d10'
down_revision = 'e9da14f42615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratory', 'address')
    # ### end Alembic commands ###
