"""renmed mtm activity keys

Revision ID: 8a92e453b2ef
Revises: 23e960248fb1
Create Date: 2021-12-05 13:54:39.151764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8a92e453b2ef'
down_revision = '23e960248fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_feed_subscription', sa.Column('activity_feed_uid', sa.Integer(), nullable=False))
    op.drop_constraint('activity_feed_subscription_feed_uid_fkey', 'activity_feed_subscription', type_='foreignkey')
    op.create_foreign_key(None, 'activity_feed_subscription', 'activityfeed', ['activity_feed_uid'], ['uid'])
    op.drop_column('activity_feed_subscription', 'feed_uid')
    op.add_column('activity_stream_feed', sa.Column('activity_feed_uid', sa.Integer(), nullable=False))
    op.drop_constraint('activity_stream_feed_feed_uid_fkey', 'activity_stream_feed', type_='foreignkey')
    op.create_foreign_key(None, 'activity_stream_feed', 'activityfeed', ['activity_feed_uid'], ['uid'])
    op.drop_column('activity_stream_feed', 'feed_uid')
    op.add_column('activity_stream_view', sa.Column('activity_stream_uid', sa.Integer(), nullable=False))
    op.drop_constraint('activity_stream_view_stream_uid_fkey', 'activity_stream_view', type_='foreignkey')
    op.create_foreign_key(None, 'activity_stream_view', 'activitystream', ['activity_stream_uid'], ['uid'])
    op.drop_column('activity_stream_view', 'stream_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_stream_view', sa.Column('stream_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_stream_view', type_='foreignkey')
    op.create_foreign_key('activity_stream_view_stream_uid_fkey', 'activity_stream_view', 'activitystream', ['stream_uid'], ['uid'])
    op.drop_column('activity_stream_view', 'activity_stream_uid')
    op.add_column('activity_stream_feed', sa.Column('feed_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_stream_feed', type_='foreignkey')
    op.create_foreign_key('activity_stream_feed_feed_uid_fkey', 'activity_stream_feed', 'activityfeed', ['feed_uid'], ['uid'])
    op.drop_column('activity_stream_feed', 'activity_feed_uid')
    op.add_column('activity_feed_subscription', sa.Column('feed_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_feed_subscription', type_='foreignkey')
    op.create_foreign_key('activity_feed_subscription_feed_uid_fkey', 'activity_feed_subscription', 'activityfeed', ['feed_uid'], ['uid'])
    op.drop_column('activity_feed_subscription', 'activity_feed_uid')
    # ### end Alembic commands ###
