"""added profile andlysis backpop lazy load

Revision ID: 915ea9ad7042
Revises: df2a087f61b7
Create Date: 2021-09-29 09:48:30.090772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '915ea9ad7042'
down_revision = 'df2a087f61b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
