"""added storage slot index

Revision ID: 981e85722e83
Revises: 7a2dac5d7e56
Create Date: 2023-01-14 11:09:21.537517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981e85722e83'
down_revision = '7a2dac5d7e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('storage_slot_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'storage_slot_index')
    # ### end Alembic commands ###
