"""added profile_sample_type

Revision ID: 9b3d6e9ba0e7
Revises: 4aa53e8318cc
Create Date: 2022-03-13 12:10:30.332184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9b3d6e9ba0e7'
down_revision = '4aa53e8318cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_sample_type',
    sa.Column('sample_type_uid', sa.Integer(), nullable=False),
    sa.Column('profile_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], ),
    sa.ForeignKeyConstraint(['sample_type_uid'], ['sampletype.uid'], ),
    sa.PrimaryKeyConstraint('sample_type_uid', 'profile_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_sample_type')
    # ### end Alembic commands ###
