"""added joined load to sample

Revision ID: a7d1a3f58706
Revises: 3af263066ae3
Create Date: 2021-09-26 09:18:27.832970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a7d1a3f58706'
down_revision = '3af263066ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
