"""added thread deletion and recipients

Revision ID: b1097c414193
Revises: a2c49e3623a0
Create Date: 2021-12-05 13:08:23.838930

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b1097c414193'
down_revision = 'a2c49e3623a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_thread_delete',
    sa.Column('thread_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_uid'], ['messagethread.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('thread_uid', 'user_uid')
    )
    op.create_table('message_thread_recipient',
    sa.Column('thread_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_uid'], ['messagethread.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('thread_uid', 'user_uid')
    )
    op.drop_table('message_recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_recipient',
    sa.Column('message_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_uid'], ['message.uid'], name='message_recipient_message_uid_fkey'),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], name='message_recipient_user_uid_fkey'),
    sa.PrimaryKeyConstraint('message_uid', 'user_uid', name='message_recipient_pkey')
    )
    op.drop_table('message_thread_recipient')
    op.drop_table('message_thread_delete')
    # ### end Alembic commands ###
