"""updated setting route

Revision ID: ba9fb2f8a8f8
Revises: 28850bad126e
Create Date: 2022-03-01 14:19:58.132095

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ba9fb2f8a8f8'
down_revision = '28850bad126e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
