"""remapped user table to user preferences

Revision ID: c4d78005a89f
Revises: 29e59fa4700f
Create Date: 2022-03-20 10:54:35.533837

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4d78005a89f'
down_revision = '29e59fa4700f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultmutation',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_uid', sa.Integer(), nullable=False),
    sa.Column('before', sa.String(), nullable=False),
    sa.Column('after', sa.String(), nullable=False),
    sa.Column('mutation', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_uid', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['result_uid'], ['analysisresult.uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_resultmutation_uid'), 'resultmutation', ['uid'], unique=False)
    op.add_column('user', sa.Column('preference_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'userpreference', ['preference_uid'], ['uid'])
    op.drop_constraint('userpreference_user_uid_fkey', 'userpreference', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('userpreference_user_uid_fkey', 'userpreference', 'user', ['user_uid'], ['uid'])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'preference_uid')
    op.drop_index(op.f('ix_resultmutation_uid'), table_name='resultmutation')
    op.drop_table('resultmutation')
    # ### end Alembic commands ###
