"""added keyword default to name

Revision ID: d69df6d3b2af
Revises: 34064732a041
Create Date: 2021-11-07 07:56:33.852859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd69df6d3b2af'
down_revision = '34064732a041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'keyword',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'keyword',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
