"""updated setting route c

Revision ID: de043716c3ff
Revises: ba9fb2f8a8f8
Create Date: 2022-03-01 14:21:27.836502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'de043716c3ff'
down_revision = 'ba9fb2f8a8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
