"""replaced backref with backpop for grops and members

Revision ID: df15a29a7932
Revises: a7d1a3f58706
Create Date: 2021-09-26 11:11:19.504991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'df15a29a7932'
down_revision = 'a7d1a3f58706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
