"""rmvd joined load for group amd user

Revision ID: df2a087f61b7
Revises: 2954d3753ce9
Create Date: 2021-09-26 11:21:30.399114

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'df2a087f61b7'
down_revision = '2954d3753ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
