"""added streams, notices, feeds, notification models

Revision ID: e449fc441562
Revises: 747fbd6576dc
Create Date: 2021-12-04 21:55:56.807413

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e449fc441562'
down_revision = '747fbd6576dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activityfeed',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by_uid', sa.Integer(), nullable=True),
    sa.Column('updated_by_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_activityfeed_uid'), 'activityfeed', ['uid'], unique=False)
    op.create_table('activitystream',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_uid', sa.Integer(), nullable=True),
    sa.Column('verb', sa.String(), nullable=True),
    sa.Column('action_object_uid', sa.Integer(), nullable=True),
    sa.Column('action_object', sa.String(), nullable=True),
    sa.Column('target_uid', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('created_by_uid', sa.Integer(), nullable=True),
    sa.Column('updated_by_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_activitystream_uid'), 'activitystream', ['uid'], unique=False)
    op.create_table('notice',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('created_by_uid', sa.Integer(), nullable=True),
    sa.Column('updated_by_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_notice_uid'), 'notice', ['uid'], unique=False)
    op.create_table('notification',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_by_uid', sa.Integer(), nullable=True),
    sa.Column('updated_by_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_notification_uid'), 'notification', ['uid'], unique=False)
    op.create_table('activity_feed_subscription',
    sa.Column('feed_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_uid'], ['activityfeed.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('feed_uid', 'user_uid')
    )
    op.create_table('activity_stream_feed',
    sa.Column('feed_uid', sa.Integer(), nullable=False),
    sa.Column('stream_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_uid'], ['activityfeed.uid'], ),
    sa.ForeignKeyConstraint(['stream_uid'], ['activitystream.uid'], ),
    sa.PrimaryKeyConstraint('feed_uid', 'stream_uid')
    )
    op.create_table('activity_stream_view',
    sa.Column('stream_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stream_uid'], ['activitystream.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('stream_uid', 'user_uid')
    )
    op.create_table('department_notice',
    sa.Column('notice_uid', sa.Integer(), nullable=False),
    sa.Column('department_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_uid'], ['department.uid'], ),
    sa.ForeignKeyConstraint(['notice_uid'], ['notice.uid'], ),
    sa.PrimaryKeyConstraint('notice_uid', 'department_uid')
    )
    op.create_table('department_notification',
    sa.Column('notification_uid', sa.Integer(), nullable=False),
    sa.Column('department_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_uid'], ['department.uid'], ),
    sa.ForeignKeyConstraint(['notification_uid'], ['notification.uid'], ),
    sa.PrimaryKeyConstraint('notification_uid', 'department_uid')
    )
    op.create_table('group_notice',
    sa.Column('notice_uid', sa.Integer(), nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['group.uid'], ),
    sa.ForeignKeyConstraint(['notice_uid'], ['notice.uid'], ),
    sa.PrimaryKeyConstraint('notice_uid', 'group_uid')
    )
    op.create_table('group_notification',
    sa.Column('notification_uid', sa.Integer(), nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['group.uid'], ),
    sa.ForeignKeyConstraint(['notification_uid'], ['notification.uid'], ),
    sa.PrimaryKeyConstraint('notification_uid', 'group_uid')
    )
    op.create_table('notice_view',
    sa.Column('notice_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notice_uid'], ['notice.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('notice_uid', 'user_uid')
    )
    op.create_table('notification_view',
    sa.Column('notification_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_uid'], ['notification.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('notification_uid', 'user_uid')
    )
    op.create_table('user_notification',
    sa.Column('notification_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_uid'], ['notification.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('notification_uid', 'user_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification')
    op.drop_table('notification_view')
    op.drop_table('notice_view')
    op.drop_table('group_notification')
    op.drop_table('group_notice')
    op.drop_table('department_notification')
    op.drop_table('department_notice')
    op.drop_table('activity_stream_view')
    op.drop_table('activity_stream_feed')
    op.drop_table('activity_feed_subscription')
    op.drop_index(op.f('ix_notification_uid'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_notice_uid'), table_name='notice')
    op.drop_table('notice')
    op.drop_index(op.f('ix_activitystream_uid'), table_name='activitystream')
    op.drop_table('activitystream')
    op.drop_index(op.f('ix_activityfeed_uid'), table_name='activityfeed')
    op.drop_table('activityfeed')
    # ### end Alembic commands ###
