"""addeed pages

Revision ID: f79972cacf70
Revises: 88261aa91d10
Create Date: 2022-03-02 23:56:47.626687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f79972cacf70'
down_revision = '88261aa91d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('pages', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'pages')
    # ### end Alembic commands ###
