<script setup lang="ts">
import accordion from "../../components/Accordion.vue";
import { reactive, onMounted } from "vue";
import axios from "../../axios/with-auth";
import { REST_BASE_URL } from "../../conf";
import { useNotifyToast } from "../../composables";
import { IReportListing } from "../../models/reports";

const { toastSuccess, toastWarning } = useNotifyToast();

const state = reactive({
  reports: [] as IReportListing[],
  listingForm: {
    report_type: "",
    analyses_uids: [],
    sample_states: [],
    date_column: "",
    period_start: "",
    period_end: "",
  } as IReportListing,
});

onMounted(async () => {
  await axios.get("reports").then((resp) => {
    state.reports = resp.data;
  });
});

const saveListingForm = () => {
  const request = { ...state.listingForm };
  axios.post("reports", request).then((resp) => {
    state.reports.push(resp.data);
  });
};

const downloadReport = (report: any) => {
  const link = document.createElement("a");
  link.download = report.report_type + "-" + report.crated_at;
  link.href = REST_BASE_URL + "/" + report.location;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

const deleteReport = (report: any) => {
  axios.delete("reports/" + report.uid).then((resp) => {
    const data = resp.data;
    const index = state.reports.findIndex((x) => x.uid === data.uid);
    if (index > -1) {
      state!.reports.splice(index, 1);
      toastSuccess(data.message);
    } else {
      toastWarning("Failed to remove report: Please refresh your page");
    }
  });
};
</script>

<template>
  <accordion>
    <template v-slot:title>Downloaded Line Listing Reports</template>
    <template v-slot:body>
      <div class="overflow-x-auto mt-4">
        <div
          v-if="state.reports?.length > 0"
          class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-2 pt-1 rounded-bl-sm rounded-br-sm"
        >
          <table class="min-w-full">
            <thead>
              <tr>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left leading-4 text-gray-800 tracking-wider"
                >
                  <input type="checkbox" />
                </th>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left leading-4 text-gray-800 tracking-wider"
                >
                  Report Type
                </th>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left text-sm leading-4 text-gray-800 tracking-wider"
                >
                  Generated By
                </th>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left text-sm leading-4 text-gray-800 tracking-wider"
                >
                  Date Generated
                </th>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left text-sm leading-4 text-gray-800 tracking-wider"
                >
                  Period Start
                </th>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left text-sm leading-4 text-gray-800 tracking-wider"
                >
                  Period End
                </th>
                <th
                  class="px-1 py-1 border-b-2 border-gray-300 text-left text-sm leading-4 text-gray-800 tracking-wider"
                >
                  Status
                </th>
                <th class="px-1 py-1 border-b-2 border-gray-300"></th>
              </tr>
            </thead>
            <tbody class="bg-white">
              <tr v-for="report in state.reports" :key="report.uid">
                <td>
                  <input type="checkbox" />
                </td>
                <td class="px-1 py-1 whitespace-no-wrap border-b border-gray-500">
                  <div class="text-sm leading-5 text-sky-800">
                    {{ report.report_type }}
                  </div>
                </td>
                <td class="px-1 py-1 whitespace-no-wrap border-b border-gray-500">
                  <div class="text-sm leading-5 text-sky-800">
                    {{ report?.created_by?.first_name }}
                    {{ report?.created_by?.last_name }}
                  </div>
                </td>
                <td class="px-1 py-1 whitespace-no-wrap border-b border-gray-500">
                  <div class="text-sm leading-5 text-sky-800">
                    {{ report?.created_at }}
                  </div>
                </td>
                <td class="px-1 py-1 whitespace-no-wrap border-b border-gray-500">
                  <div class="text-sm leading-5 text-sky-800">
                    {{ report?.period_start }}
                  </div>
                </td>
                <td class="px-1 py-1 whitespace-no-wrap border-b border-gray-500">
                  <div class="text-sm leading-5 text-sky-800">
                    {{ report?.period_end }}
                  </div>
                </td>
                <td class="px-1 py-1 whitespace-no-wrap border-b border-gray-500">
                  <div class="text-sm leading-5 text-sky-800">{{ report?.status }}</div>
                </td>
                <td
                  class="px-1 py-1 whitespace-no-wrap text-right border-b border-gray-500 text-sm leading-5"
                >
                  <button
                    v-show="report.status == 'READY'"
                    @click="downloadReport(report)"
                    class="px-2 py-1 mr-2 border-sky-800 border text-sky-800rounded-smtransition duration-300 hover:bg-sky-800 hover:text-white focus:outline-none"
                  >
                    Download
                  </button>
                  <button
                    v-show="report.status == 'READY'"
                    @click="deleteReport(report)"
                    class="px-2 py-1 mr-2 border-orange-600 border text-orange-600rounded-smtransition duration-300 hover:bg-orange-600 hover:text-white focus:outline-none"
                  >
                    Delete
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div v-else class="py-4 pl-4 bg-white">
          <p class="text-orange-600">There are no downloaded reports yet</p>
          <hr />
          <p class="italic">
            Once a download request has been done. Your reports will be appear here
          </p>
        </div>
      </div>
    </template>
  </accordion>

  <accordion>
    <template v-slot:title>Listing Report Request</template>
    <template v-slot:body>
      <div class="overflow-x-auto mt-4">
        <form action="post" class="p-1">
          <div class="grid grid-cols-3 gap-x-4 mb-4">
            <label class="block col-span-1 mb-2">
              <span class="text-gray-700">Report Type</span>
              <select
                name="report_type"
                v-model="state.listingForm.report_type"
                class="form-input mt-1 block w-full"
              >
                <option value="line_listing" selected>line listing</option>
              </select>
            </label>
            <label class="block col-span-1 mb-2">
              <span class="text-gray-700">Analyses</span>
              <select
                name="analyses_uids"
                v-model="state.listingForm.analyses_uids"
                class="form-input mt-1 block w-full"
                multiple
              >
                <option value=""></option>
                <option value="1">EID</option>
              </select>
            </label>
            <label class="block col-span-1 mb-2">
              <span class="text-gray-700">States</span>
              <select
                name="sample_states"
                v-model="state.listingForm.sample_states"
                class="form-input mt-1 block w-full"
                multiple
              >
                <option value=""></option>
                <option value="published">published</option>
                <option value="verified">verified</option>
                <option value="to_be_verified">to_be_verified</option>
                <option value="received">received</option>
                <option value="cancelled">cancelled</option>
                <option value="rejected">rejected</option>
                <option value="invalidated">invalidated</option>
                <option value="due">due</option>
              </select>
            </label>
          </div>
          <div class="grid grid-cols-3 gap-x-4 mb-4">
            <label class="block col-span-1 mb-2">
              <span class="text-gray-700">Period Date Criteria</span>
              <select
                name="date_column"
                v-model="state.listingForm.date_column"
                class="form-input mt-1 block w-full"
              >
                <option value="created_at">Created Date</option>
                <option value="date_published">Published Date</option>
                <option value="date_submitted">Submission Date</option>
                <option value="date_verified">Verified Date</option>
                <option value="date_cancelled">Cacellation Date</option>
                <option value="date_invalidated">Invalidation Date</option>
              </select>
            </label>
            <label class="block col-span-1 mb-2">
              <span class="text-gray-700">Period Start</span>
              <input
                name="period_start"
                type="datetime-local"
                class="form-input mt-1 block w-full"
                autocomplete="off"
                v-model="state.listingForm.period_start"
                placeholder="From ..."
              />
            </label>
            <label class="block col-span-1 mb-2">
              <span class="text-gray-700">Period End</span>
              <input
                name="period_end"
                type="datetime-local"
                class="form-input mt-1 block w-full"
                v-model="state.listingForm.period_end"
                placeholder="To ..."
              />
            </label>
          </div>
          <hr />
          <button
            type="button"
            @click.prevent="saveListingForm()"
            class="-mb-4 w-full border border-sky-800 bg-sky-800 text-white rounded-sm px-4 py-2 m-2 transition-colors duration-500 ease select-none hover:bg-sky-800 focus:outline-none focus:shadow-outline"
          >
            Save Form
          </button>
        </form>
      </div>
    </template>
  </accordion>
</template>
