const pages = {
    LOGIN: "LOGIN",
    DASHBOARD: "DASHBOARD",
    PATIENTS: "PATIENTS",
    PATIENTS_COMPACT: "PATIENTS_COMPACT",
    CLIENTS: "CLIENTS",
    SAMPLES: "SAMPLES",
    QC_SAMPLES: "QC_SAMPLES",
    WORKSHEETS: "WORKSHEETS",
    KANBAN_BOARD: "KANBAN_BOARD",
    MARKDOWN_DOCUMENTS: "MARKDOWN_DOCUMENTS",
    NOTICE_MANAGER: "NOTICE_MANAGER",
    NOT_AUTHORISED: "NOT_AUTHORISED",
    ADMINISTRATION: "ADMINISTRATION",
    FOUR_OR_FOUR: "FOUR_OR_FOUR",
  };
  

export { pages };