const pages = {
    LOGIN: "LOGIN",
    DASHBOARD: "DASHBOARD",
    PATIENTS: "PATIENTS",
    PATIENTS_COMPACT: "PATIENTS_COMPACT",
    CLIENTS: "CLIENTS",
    SAMPLES: "SAMPLES",
    QC_SAMPLES: "QC_SAMPLES",
    WORKSHEETS: "WORKSHEETS",
    NOTICE_MANAGER: "NOTICE_MANAGER",
    ADMINISTRATION: "ADMINISTRATION",
    REFLEX_RULES: "REFLEX_RULES",
    NOT_AUTHORISED: "NOT_AUTHORISED",
    FOUR_OR_FOUR: "FOUR_OR_FOUR",
    INSTALLATION: "INSTALLATION",
};
  

export { pages };