"""rethought identifications 2

Revision ID: 1ef66812cd10
Revises: 443bbf86aba8
Create Date: 2023-04-09 13:47:10.552259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef66812cd10'
down_revision = '443bbf86aba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
