from felicity.database.base_class import DBModel  # noqa
from felicity.apps.audit.models import AuditLog  # noqa
from felicity.apps.setup.models import Country  # noqa
from felicity.apps.setup.models import Province  # noqa
from felicity.apps.setup.models import District  # noqa
from felicity.apps.setup.models import Laboratory  # noqa
from felicity.apps.setup.models import Department  # noqa
from felicity.apps.setup.models import Supplier  # noqa
from felicity.apps.setup.models import Instrument  # noqa
from felicity.apps.setup.models import Method  # noqa
from felicity.apps.user.models import UserAuth  # noqa
from felicity.apps.user.models import User  # noqa
from felicity.apps.user.models import Permission  # noqa
from felicity.apps.user.models import Group  # noqa
from felicity.apps.client.models import Client  # noqa
from felicity.apps.client.models import ClientContact  # noqa
from felicity.apps.patient.models import Patient  # noqa
from felicity.apps.analysis.models.analysis import SampleType  # noqa
from felicity.apps.analysis.models.analysis import Analysis  # noqa
from felicity.apps.analysis.models.analysis import Profile  # noqa
from felicity.apps.analysis.models.analysis import Sample  # noqa
from felicity.apps.analysis.models.analysis import ResultOption  # noqa
from felicity.apps.analysis.models.analysis import RejectionReason  # noqa
from felicity.apps.analysis.models.analysis import AnalysisRequest  # noqa
from felicity.apps.analysis.models.results import AnalysisResult  # noqa
from felicity.apps.analysis.models.analysis import AnalysisCategory  # noqa
from felicity.apps.analysis.models.qc import QCTemplate  # noqa
from felicity.apps.worksheet.models import WorkSheetTemplate  # noqa
from felicity.apps.worksheet.models import WorkSheet  # noqa
from felicity.apps.job.models import Job  # noqa
from felicity.apps.markdown.models import DocumentTag  # noqa
from felicity.apps.markdown.models import DocumentCategory  # noqa
from felicity.apps.markdown.models import Document  # noqa
from felicity.apps.kanban.models import Board  # noqa
from felicity.apps.kanban.models import BoardListing  # noqa
from felicity.apps.kanban.models import ListingTask  # noqa
from felicity.apps.kanban.models import TaskTag  # noqa
from felicity.apps.kanban.models import TaskMilestone  # noqa
from felicity.apps.kanban.models import TaskComment  # noqa
