"""ini felicity Tue Jan  5 11:01:30 UTC 2021

Revision ID: 0261a24a4c16
Revises: 281ce8e37b58
Create Date: 2021-01-05 11:01:31.807870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0261a24a4c16'
down_revision = '281ce8e37b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('client_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient', 'client', ['client_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'client_uid')
    # ### end Alembic commands ###
