"""added qc dpt fkey

Revision ID: 0552e86b4918
Revises: 27c1bc5dedec
Create Date: 2021-05-29 13:10:36.859669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0552e86b4918'
down_revision = '27c1bc5dedec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qctdlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_uid', sa.Integer(), nullable=False),
    sa.Column('qc_template_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_uid'], ['department.uid'], ),
    sa.ForeignKeyConstraint(['qc_template_uid'], ['qctemplate.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'department_uid', 'qc_template_uid')
    )
    op.create_index(op.f('ix_qctdlink_uid'), 'qctdlink', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qctdlink_uid'), table_name='qctdlink')
    op.drop_table('qctdlink')
    # ### end Alembic commands ###
