"""ini felicity Sat Mar 27 08:21:56 UTC 2021

Revision ID: 09e2d053c0e1
Revises: beee9a5665a1
Create Date: 2021-03-27 08:21:56.807985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e2d053c0e1'
down_revision = 'beee9a5665a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
