"""ws_uid nulab;e

Revision ID: 0d4a032b7ad8
Revises: 0e30436eeefb
Create Date: 2021-04-11 03:15:56.970989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4a032b7ad8'
down_revision = '0e30436eeefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
