"""ini felicity Sat Mar 27 08:21:28 UTC 2021

Revision ID: 0efaa896c1a0
Revises: 
Create Date: 2021-03-27 08:21:28.687350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efaa896c1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
