"""trial 2

Revision ID: 154fc4f2bda8
Revises: 6a2e0f4f31a4
Create Date: 2021-05-29 20:25:10.280743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154fc4f2bda8'
down_revision = '6a2e0f4f31a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
