"""ini felicity Sat Mar 27 08:22:39 UTC 2021

Revision ID: 2183bf752222
Revises: c01bbbfe44db
Create Date: 2021-03-27 08:22:40.358605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2183bf752222'
down_revision = 'c01bbbfe44db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
