"""added qc templatetable

Revision ID: 27c1bc5dedec
Revises: 0d5a6d453ad9
Create Date: 2021-05-29 12:32:00.957644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c1bc5dedec'
down_revision = '0d5a6d453ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qctemplate',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_qctemplate_uid'), 'qctemplate', ['uid'], unique=False)
    op.create_table('qctalink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.Column('qc_template_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['qc_template_uid'], ['qctemplate.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'analysis_uid', 'qc_template_uid')
    )
    op.create_index(op.f('ix_qctalink_uid'), 'qctalink', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qctalink_uid'), table_name='qctalink')
    op.drop_table('qctalink')
    op.drop_index(op.f('ix_qctemplate_uid'), table_name='qctemplate')
    op.drop_table('qctemplate')
    # ### end Alembic commands ###
