"""added audit log table and mixin - not wired yet

Revision ID: 2d53f7a72dcc
Revises: 3c760ffbf383
Create Date: 2021-04-21 07:29:26.091159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d53f7a72dcc'
down_revision = '3c760ffbf383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('state_before', sa.UnicodeText(), nullable=True),
    sa.Column('state_after', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_auditlog_uid'), 'auditlog', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditlog_uid'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
