"""addes cascades for delete

Revision ID: 4613125f6afc
Revises: f0ea6141f58f
Create Date: 2021-09-10 03:05:45.262310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4613125f6afc'
down_revision = 'f0ea6141f58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('taskcomment_commenter_uid_fkey', 'taskcomment', type_='foreignkey')
    op.drop_column('taskcomment', 'commenter_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskcomment', sa.Column('commenter_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('taskcomment_commenter_uid_fkey', 'taskcomment', 'user', ['commenter_uid'], ['uid'])
    # ### end Alembic commands ###
