"""added permission and groups tables

Revision ID: 479f77fdb5b9
Revises: 69dae1cea070
Create Date: 2021-04-14 17:04:40.052390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479f77fdb5b9'
down_revision = '69dae1cea070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_index(op.f('ix_group_uid'), 'group', ['uid'], unique=False)
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_permission_action'), 'permission', ['action'], unique=True)
    op.create_index(op.f('ix_permission_uid'), 'permission', ['uid'], unique=False)
    op.create_table('gplink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_uid', sa.Integer(), nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['group.uid'], ),
    sa.ForeignKeyConstraint(['permission_uid'], ['permission.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'permission_uid', 'group_uid')
    )
    op.create_index(op.f('ix_gplink_uid'), 'gplink', ['uid'], unique=False)
    op.create_table('gulink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['group.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'user_uid', 'group_uid')
    )
    op.create_index(op.f('ix_gulink_uid'), 'gulink', ['uid'], unique=False)
    op.alter_column('worksheet', 'assigned_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worksheet', 'assigned_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_gulink_uid'), table_name='gulink')
    op.drop_table('gulink')
    op.drop_index(op.f('ix_gplink_uid'), table_name='gplink')
    op.drop_table('gplink')
    op.drop_index(op.f('ix_permission_uid'), table_name='permission')
    op.drop_index(op.f('ix_permission_action'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_group_uid'), table_name='group')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
