"""ini felicity Sat Mar 27 08:21:30 UTC 2021

Revision ID: 48ba93bb41fc
Revises: 0efaa896c1a0
Create Date: 2021-03-27 08:21:31.481674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ba93bb41fc'
down_revision = '0efaa896c1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
