"""updated doc readers

Revision ID: 535a4d0bf16a
Revises: 81a406cfd39f
Create Date: 2021-05-06 17:45:36.770572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '535a4d0bf16a'
down_revision = '81a406cfd39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docreaders',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_uid'], ['document.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'document_uid', 'user_uid')
    )
    op.create_index(op.f('ix_docreaders_uid'), 'docreaders', ['uid'], unique=False)
    op.drop_index('ix_docreads_uid', table_name='docreads')
    op.drop_table('docreads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docreads',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_uid'], ['document.uid'], name='docreads_document_uid_fkey'),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], name='docreads_user_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', 'document_uid', 'user_uid', name='docreads_pkey')
    )
    op.create_index('ix_docreads_uid', 'docreads', ['uid'], unique=False)
    op.drop_index(op.f('ix_docreaders_uid'), table_name='docreaders')
    op.drop_table('docreaders')
    # ### end Alembic commands ###
