"""add audit track fields

Revision ID: 55a4e324d0f5
Revises: e6400d83bab9
Create Date: 2021-09-05 18:03:26.572382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a4e324d0f5'
down_revision = 'e6400d83bab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('date_submitted', sa.DateTime(), nullable=True))
    op.add_column('sample', sa.Column('date_verified', sa.DateTime(), nullable=True))
    op.add_column('sample', sa.Column('submitted_by_uid', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('verified_by_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'user', ['submitted_by_uid'], ['uid'])
    op.create_foreign_key(None, 'sample', 'user', ['verified_by_uid'], ['uid'])
    op.add_column('worksheet', sa.Column('created_by_uid', sa.Integer(), nullable=True))
    op.add_column('worksheet', sa.Column('date_submitted', sa.DateTime(), nullable=True))
    op.add_column('worksheet', sa.Column('date_verified', sa.DateTime(), nullable=True))
    op.add_column('worksheet', sa.Column('submitted_by_uid', sa.Integer(), nullable=True))
    op.add_column('worksheet', sa.Column('updated_by_uid', sa.Integer(), nullable=True))
    op.add_column('worksheet', sa.Column('verified_by_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'worksheet', 'user', ['verified_by_uid'], ['uid'])
    op.create_foreign_key(None, 'worksheet', 'user', ['updated_by_uid'], ['uid'])
    op.create_foreign_key(None, 'worksheet', 'user', ['created_by_uid'], ['uid'])
    op.create_foreign_key(None, 'worksheet', 'user', ['submitted_by_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worksheet', type_='foreignkey')
    op.drop_constraint(None, 'worksheet', type_='foreignkey')
    op.drop_constraint(None, 'worksheet', type_='foreignkey')
    op.drop_constraint(None, 'worksheet', type_='foreignkey')
    op.drop_column('worksheet', 'verified_by_uid')
    op.drop_column('worksheet', 'updated_by_uid')
    op.drop_column('worksheet', 'submitted_by_uid')
    op.drop_column('worksheet', 'date_verified')
    op.drop_column('worksheet', 'date_submitted')
    op.drop_column('worksheet', 'created_by_uid')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'verified_by_uid')
    op.drop_column('sample', 'submitted_by_uid')
    op.drop_column('sample', 'date_verified')
    op.drop_column('sample', 'date_submitted')
    # ### end Alembic commands ###
