"""ini felicity Sun Mar 14 06:14:05 UTC 2021

Revision ID: 5af557562889
Revises: e8ebc3a35350
Create Date: 2021-03-14 06:14:06.882460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af557562889'
down_revision = 'e8ebc3a35350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clientcontact_email', table_name='clientcontact')
    op.create_index(op.f('ix_clientcontact_email'), 'clientcontact', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientcontact_email'), table_name='clientcontact')
    op.create_index('ix_clientcontact_email', 'clientcontact', ['email'], unique=True)
    # ### end Alembic commands ###
