"""count asigned analyses

Revision ID: 69dae1cea070
Revises: 8c5315b1cfce
Create Date: 2021-04-11 10:07:03.280325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69dae1cea070'
down_revision = '8c5315b1cfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worksheet', sa.Column('assigned_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worksheet', 'assigned_count')
    # ### end Alembic commands ###
