"""trial

Revision ID: 6a2e0f4f31a4
Revises: c083d9d8d9f3
Create Date: 2021-05-29 20:21:18.850115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2e0f4f31a4'
down_revision = 'c083d9d8d9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
