"""addes cascades for delete for board listing

Revision ID: 6d8b615469cd
Revises: 4613125f6afc
Create Date: 2021-09-11 07:04:31.727117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8b615469cd'
down_revision = '4613125f6afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
