"""reset

Revision ID: 79c3917c4d01
Revises: 154fc4f2bda8
Create Date: 2021-05-29 20:34:42.779150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c3917c4d01'
down_revision = '154fc4f2bda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
