"""renamed ws field

Revision ID: 7e601bb83c38
Revises: e34ab8a0d51c
Create Date: 2021-04-06 23:33:15.735340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e601bb83c38'
down_revision = 'e34ab8a0d51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
