"""ini felicity Sat Mar 27 08:25:37 UTC 2021

Revision ID: 815cdbefca6a
Revises: 55728fd9ffe6
Create Date: 2021-03-27 08:25:38.135237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815cdbefca6a'
down_revision = '55728fd9ffe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
