"""updated backrefs to makedowns

Revision ID: 81a406cfd39f
Revises: dbb7632f9004
Create Date: 2021-05-06 17:42:49.417456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a406cfd39f'
down_revision = 'dbb7632f9004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
