"""made ar in same not mandatory

Revision ID: 8f6bbe151856
Revises: a9f58c1801eb
Create Date: 2021-05-29 21:40:19.890282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6bbe151856'
down_revision = 'a9f58c1801eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'analysisrequest_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample', 'sampletype_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'sampletype_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample', 'analysisrequest_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
