"""ini felicity Sat Mar 13 14:48:26 UTC 2021

Revision ID: a2697aa33462
Revises: fbf42f604bbb
Create Date: 2021-03-13 14:48:27.772941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2697aa33462'
down_revision = 'fbf42f604bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysisresult', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('analysisresult', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('analysisresult', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('analysisresult', sa.Column('rgt', sa.Integer(), nullable=False))
    op.add_column('analysisresult', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_analysisresult_level'), 'analysisresult', ['level'], unique=False)
    op.create_index(op.f('ix_analysisresult_lft'), 'analysisresult', ['lft'], unique=False)
    op.create_index(op.f('ix_analysisresult_rgt'), 'analysisresult', ['rgt'], unique=False)
    op.create_foreign_key(None, 'analysisresult', 'analysisresult', ['parent_id'], ['uid'], ondelete='CASCADE')
    op.add_column('clientcontact', sa.Column('client_uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clientcontact', 'client', ['client_uid'], ['uid'])
    op.add_column('sample', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('sample', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('sample', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('sample', sa.Column('rgt', sa.Integer(), nullable=False))
    op.add_column('sample', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sample_level'), 'sample', ['level'], unique=False)
    op.create_index(op.f('ix_sample_lft'), 'sample', ['lft'], unique=False)
    op.create_index(op.f('ix_sample_rgt'), 'sample', ['rgt'], unique=False)
    op.create_foreign_key(None, 'sample', 'sample', ['parent_id'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_index(op.f('ix_sample_rgt'), table_name='sample')
    op.drop_index(op.f('ix_sample_lft'), table_name='sample')
    op.drop_index(op.f('ix_sample_level'), table_name='sample')
    op.drop_column('sample', 'tree_id')
    op.drop_column('sample', 'rgt')
    op.drop_column('sample', 'parent_id')
    op.drop_column('sample', 'lft')
    op.drop_column('sample', 'level')
    op.drop_constraint(None, 'clientcontact', type_='foreignkey')
    op.drop_column('clientcontact', 'client_uid')
    op.drop_constraint(None, 'analysisresult', type_='foreignkey')
    op.drop_index(op.f('ix_analysisresult_rgt'), table_name='analysisresult')
    op.drop_index(op.f('ix_analysisresult_lft'), table_name='analysisresult')
    op.drop_index(op.f('ix_analysisresult_level'), table_name='analysisresult')
    op.drop_column('analysisresult', 'tree_id')
    op.drop_column('analysisresult', 'rgt')
    op.drop_column('analysisresult', 'parent_id')
    op.drop_column('analysisresult', 'lft')
    op.drop_column('analysisresult', 'level')
    # ### end Alembic commands ###
