"""change task status fields to a boolean complete

Revision ID: a2f46e4e20c6
Revises: 6d8b615469cd
Create Date: 2021-09-11 09:19:34.248153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f46e4e20c6'
down_revision = '6d8b615469cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listingtask', sa.Column('complete', sa.Boolean(), nullable=True))
    op.drop_column('listingtask', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listingtask', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('listingtask', 'complete')
    # ### end Alembic commands ###
