"""wstaqc 2 reset

Revision ID: a9f58c1801eb
Revises: dde8c4d804e9
Create Date: 2021-05-29 21:11:07.056315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f58c1801eb'
down_revision = 'dde8c4d804e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wsaqclink', sa.Column('worksheet_uid', sa.Integer(), nullable=False))
    op.drop_constraint('wsaqclink_ws_template_uid_fkey', 'wsaqclink', type_='foreignkey')
    op.create_foreign_key(None, 'wsaqclink', 'worksheet', ['worksheet_uid'], ['uid'])
    op.drop_column('wsaqclink', 'ws_template_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wsaqclink', sa.Column('ws_template_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wsaqclink', type_='foreignkey')
    op.create_foreign_key('wsaqclink_ws_template_uid_fkey', 'wsaqclink', 'worksheettemplate', ['ws_template_uid'], ['uid'])
    op.drop_column('wsaqclink', 'worksheet_uid')
    # ### end Alembic commands ###
