"""added internal use to analysies

Revision ID: ba0b79a5bb9c
Revises: 27a65413f177
Create Date: 2021-05-30 11:13:39.862608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0b79a5bb9c'
down_revision = '27a65413f177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('internal_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'internal_use')
    # ### end Alembic commands ###
