"""ini felicity Sat Mar 27 08:21:47 UTC 2021

Revision ID: beee9a5665a1
Revises: 55afcb809948
Create Date: 2021-03-27 08:21:47.818169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beee9a5665a1'
down_revision = '55afcb809948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
