"""ini felicity Sat Mar 27 08:22:11 UTC 2021

Revision ID: c01bbbfe44db
Revises: 09e2d053c0e1
Create Date: 2021-03-27 08:22:12.191806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01bbbfe44db'
down_revision = '09e2d053c0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
