"""added qc description

Revision ID: c083d9d8d9f3
Revises: 0552e86b4918
Create Date: 2021-05-29 13:34:41.238373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c083d9d8d9f3'
down_revision = '0552e86b4918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qctemplate', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qctemplate', 'description')
    # ### end Alembic commands ###
