"""added analysis models and job models

Revision ID: c0a120db23c1
Revises: 9d5d64f59fbd
Create Date: 2021-02-15 08:52:40.865122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a120db23c1'
down_revision = '9d5d64f59fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index(op.f('ix_analysis_uid'), 'analysis', ['uid'], unique=False)
    op.create_table('job',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_job_uid'), 'job', ['uid'], unique=False)
    op.create_table('profile',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_profile_uid'), 'profile', ['uid'], unique=False)
    op.create_table('sampletype',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_sampletype_uid'), 'sampletype', ['uid'], unique=False)
    op.create_table('aplink',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.Column('profile_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'analysis_uid', 'profile_uid')
    )
    op.create_index(op.f('ix_aplink_uid'), 'aplink', ['uid'], unique=False)
    op.create_table('astlink',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sampletype_uid', sa.Integer(), nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['sampletype_uid'], ['sampletype.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'sampletype_uid', 'analysis_uid')
    )
    op.create_index(op.f('ix_astlink_uid'), 'astlink', ['uid'], unique=False)
    op.create_table('analysisrequest',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_uid', sa.Integer(), nullable=True),
    sa.Column('client_uid', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('client_request_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_uid'], ['client.uid'], ),
    sa.ForeignKeyConstraint(['patient_uid'], ['patient.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_analysisrequest_client_request_id'), 'analysisrequest', ['client_request_id'], unique=True)
    op.create_index(op.f('ix_analysisrequest_request_id'), 'analysisrequest', ['request_id'], unique=True)
    op.create_index(op.f('ix_analysisrequest_uid'), 'analysisrequest', ['uid'], unique=False)
    op.create_table('sample',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysisrequest_uid', sa.Integer(), nullable=False),
    sa.Column('sampletype_uid', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysisrequest_uid'], ['analysisrequest.uid'], ),
    sa.ForeignKeyConstraint(['sampletype_uid'], ['sampletype.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_sample_sample_id'), 'sample', ['sample_id'], unique=True)
    op.create_index(op.f('ix_sample_uid'), 'sample', ['uid'], unique=False)
    op.create_table('analysisresult',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_uid', sa.Integer(), nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['sample_uid'], ['sample.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_analysisresult_uid'), 'analysisresult', ['uid'], unique=False)
    op.create_table('salink',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_uid', sa.Integer(), nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['sample_uid'], ['sample.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'sample_uid', 'analysis_uid')
    )
    op.create_index(op.f('ix_salink_uid'), 'salink', ['uid'], unique=False)
    op.create_table('splink',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_uid', sa.Integer(), nullable=False),
    sa.Column('profile_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], ),
    sa.ForeignKeyConstraint(['sample_uid'], ['sample.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'sample_uid', 'profile_uid')
    )
    op.create_index(op.f('ix_splink_uid'), 'splink', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_splink_uid'), table_name='splink')
    op.drop_table('splink')
    op.drop_index(op.f('ix_salink_uid'), table_name='salink')
    op.drop_table('salink')
    op.drop_index(op.f('ix_analysisresult_uid'), table_name='analysisresult')
    op.drop_table('analysisresult')
    op.drop_index(op.f('ix_sample_uid'), table_name='sample')
    op.drop_index(op.f('ix_sample_sample_id'), table_name='sample')
    op.drop_table('sample')
    op.drop_index(op.f('ix_analysisrequest_uid'), table_name='analysisrequest')
    op.drop_index(op.f('ix_analysisrequest_request_id'), table_name='analysisrequest')
    op.drop_index(op.f('ix_analysisrequest_client_request_id'), table_name='analysisrequest')
    op.drop_table('analysisrequest')
    op.drop_index(op.f('ix_astlink_uid'), table_name='astlink')
    op.drop_table('astlink')
    op.drop_index(op.f('ix_aplink_uid'), table_name='aplink')
    op.drop_table('aplink')
    op.drop_index(op.f('ix_sampletype_uid'), table_name='sampletype')
    op.drop_table('sampletype')
    op.drop_index(op.f('ix_profile_uid'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_job_uid'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_analysis_uid'), table_name='analysis')
    op.drop_table('analysis')
    # ### end Alembic commands ###
