"""refacored document models and added quries

Revision ID: dbb7632f9004
Revises: 4dfcd34ba782
Create Date: 2021-05-06 17:37:09.498459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb7632f9004'
down_revision = '4dfcd34ba782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('category_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'documentcategory', ['category_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'category_uid')
    # ### end Alembic commands ###
