"""added ws

Revision ID: e34ab8a0d51c
Revises: b528b0186f92
Create Date: 2021-04-06 23:30:35.557453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e34ab8a0d51c'
down_revision = 'b528b0186f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worksheettemplate',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worksheet_type', sa.String(), nullable=True),
    sa.Column('reserved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_samples', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('cols', sa.Integer(), nullable=True),
    sa.Column('row_wise', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instrument_uid', sa.Integer(), nullable=False),
    sa.Column('sample_type_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_uid'], ['instrument.uid'], ),
    sa.ForeignKeyConstraint(['sample_type_uid'], ['sampletype.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_worksheettemplate_uid'), 'worksheettemplate', ['uid'], unique=False)
    op.create_table('worksheet',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worksheet_type', sa.String(), nullable=True),
    sa.Column('reserved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_samples', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('cols', sa.Integer(), nullable=True),
    sa.Column('row_wise', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('template_uid', sa.Integer(), nullable=False),
    sa.Column('analyst_uid', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.String(), nullable=False),
    sa.Column('instrument_uid', sa.Integer(), nullable=False),
    sa.Column('sample_type_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analyst_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['instrument_uid'], ['instrument.uid'], ),
    sa.ForeignKeyConstraint(['sample_type_uid'], ['sampletype.uid'], ),
    sa.ForeignKeyConstraint(['template_uid'], ['worksheettemplate.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_worksheet_uid'), 'worksheet', ['uid'], unique=False)
    op.create_index(op.f('ix_worksheet_worksheet_id'), 'worksheet', ['worksheet_id'], unique=True)
    op.create_table('wstalink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ws_template_uid', sa.Integer(), nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['ws_template_uid'], ['worksheettemplate.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'ws_template_uid', 'analysis_uid')
    )
    op.create_index(op.f('ix_wstalink_uid'), 'wstalink', ['uid'], unique=False)
    op.create_table('wstplink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ws_template_uid', sa.Integer(), nullable=False),
    sa.Column('profile_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], ),
    sa.ForeignKeyConstraint(['ws_template_uid'], ['worksheettemplate.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'ws_template_uid', 'profile_uid')
    )
    op.create_index(op.f('ix_wstplink_uid'), 'wstplink', ['uid'], unique=False)
    op.create_table('wsalink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worksheet_uid', sa.Integer(), nullable=False),
    sa.Column('analysis_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_uid'], ['analysis.uid'], ),
    sa.ForeignKeyConstraint(['worksheet_uid'], ['worksheet.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'worksheet_uid', 'analysis_uid')
    )
    op.create_index(op.f('ix_wsalink_uid'), 'wsalink', ['uid'], unique=False)
    op.create_table('wsplink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worksheet_uid', sa.Integer(), nullable=False),
    sa.Column('profile_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_uid'], ['profile.uid'], ),
    sa.ForeignKeyConstraint(['worksheet_uid'], ['worksheet.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'worksheet_uid', 'profile_uid')
    )
    op.create_index(op.f('ix_wsplink_uid'), 'wsplink', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wsplink_uid'), table_name='wsplink')
    op.drop_table('wsplink')
    op.drop_index(op.f('ix_wsalink_uid'), table_name='wsalink')
    op.drop_table('wsalink')
    op.drop_index(op.f('ix_wstplink_uid'), table_name='wstplink')
    op.drop_table('wstplink')
    op.drop_index(op.f('ix_wstalink_uid'), table_name='wstalink')
    op.drop_table('wstalink')
    op.drop_index(op.f('ix_worksheet_worksheet_id'), table_name='worksheet')
    op.drop_index(op.f('ix_worksheet_uid'), table_name='worksheet')
    op.drop_table('worksheet')
    op.drop_index(op.f('ix_worksheettemplate_uid'), table_name='worksheettemplate')
    op.drop_table('worksheettemplate')
    # ### end Alembic commands ###
