"""ini felicity Sat Mar 13 14:50:30 UTC 2021

Revision ID: e8ebc3a35350
Revises: a2697aa33462
Create Date: 2021-03-13 14:50:31.784049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ebc3a35350'
down_revision = 'a2697aa33462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientcontact', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientcontact', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
