"""removed user linkages for graphql

Revision ID: ef27a0ffaf22
Revises: 535a4d0bf16a
Create Date: 2021-05-06 18:31:39.035053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef27a0ffaf22'
down_revision = '535a4d0bf16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
