"""Kanban models changes to audit tracked 2

Revision ID: f0ea6141f58f
Revises: 462219bb5136
Create Date: 2021-09-08 02:48:50.814545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ea6141f58f'
down_revision = '462219bb5136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
