"""modified billing types

Revision ID: 026a8b0275fc
Revises: a26222f9cc4e
Create Date: 2023-11-30 21:56:45.216120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026a8b0275fc'
down_revision = 'a26222f9cc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
