"""removed document ai

Revision ID: 12a5f3dc9dcb
Revises: 26f8e5d1c474
Create Date: 2025-03-16 17:04:37.795042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12a5f3dc9dcb'
down_revision = '26f8e5d1c474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_ai_compliance_check_uid', table_name='document_ai_compliance_check')
    op.drop_table('document_ai_compliance_check')
    op.drop_index('ix_document_analytics_uid', table_name='document_analytics')
    op.drop_table('document_analytics')
    op.drop_index('ix_document_ai_authoring_session_uid', table_name='document_ai_authoring_session')
    op.drop_table('document_ai_authoring_session')
    op.drop_index('ix_document_ai_review_feedback_uid', table_name='document_ai_review_feedback')
    op.drop_table('document_ai_review_feedback')
    op.drop_index('ix_document_compliance_standard_uid', table_name='document_compliance_standard')
    op.drop_table('document_compliance_standard')
    op.drop_index('ix_document_ai_model_uid', table_name='document_ai_model')
    op.drop_table('document_ai_model')
    op.drop_index('ix_document_compliance_issue_uid', table_name='document_compliance_issue')
    op.drop_table('document_compliance_issue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_compliance_issue',
    sa.Column('check_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suggestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['check_uid'], ['document_ai_compliance_check.uid'], name='document_compliance_issue_check_uid_fkey'),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_compliance_issue_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_compliance_issue_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_compliance_issue_pkey')
    )
    op.create_index('ix_document_compliance_issue_uid', 'document_compliance_issue', ['uid'], unique=False)
    op.create_table('document_ai_model',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_endpoint', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capabilities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_ai_model_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_ai_model_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_ai_model_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_document_ai_model_uid', 'document_ai_model', ['uid'], unique=False)
    op.create_table('document_compliance_standard',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_compliance_standard_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_compliance_standard_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_compliance_standard_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_document_compliance_standard_uid', 'document_compliance_standard', ['uid'], unique=False)
    op.create_table('document_ai_review_feedback',
    sa.Column('review_step_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_model_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ai_model_uid'], ['document_ai_model.uid'], name='document_ai_review_feedback_ai_model_uid_fkey'),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_ai_review_feedback_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['review_step_uid'], ['document_review_step.uid'], name='document_ai_review_feedback_review_step_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_ai_review_feedback_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_ai_review_feedback_pkey')
    )
    op.create_index('ix_document_ai_review_feedback_uid', 'document_ai_review_feedback', ['uid'], unique=False)
    op.create_table('document_ai_authoring_session',
    sa.Column('document_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_model_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conversation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ai_model_uid'], ['document_ai_model.uid'], name='document_ai_authoring_session_ai_model_uid_fkey'),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_ai_authoring_session_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['document_uid'], ['document.uid'], name='document_ai_authoring_session_document_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_ai_authoring_session_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_ai_authoring_session_pkey')
    )
    op.create_index('ix_document_ai_authoring_session_uid', 'document_ai_authoring_session', ['uid'], unique=False)
    op.create_table('document_analytics',
    sa.Column('document_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('readability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_topics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_analytics_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['document_uid'], ['document.uid'], name='document_analytics_document_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_analytics_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_analytics_pkey')
    )
    op.create_index('ix_document_analytics_uid', 'document_analytics', ['uid'], unique=False)
    op.create_table('document_ai_compliance_check',
    sa.Column('document_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('standard_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('results', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('compliance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], name='document_ai_compliance_check_created_by_uid_fkey'),
    sa.ForeignKeyConstraint(['document_uid'], ['document.uid'], name='document_ai_compliance_check_document_uid_fkey'),
    sa.ForeignKeyConstraint(['standard_uid'], ['document_compliance_standard.uid'], name='document_ai_compliance_check_standard_uid_fkey'),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], name='document_ai_compliance_check_updated_by_uid_fkey'),
    sa.PrimaryKeyConstraint('uid', name='document_ai_compliance_check_pkey')
    )
    op.create_index('ix_document_ai_compliance_check_uid', 'document_ai_compliance_check', ['uid'], unique=False)
    # ### end Alembic commands ###
