"""added external sample tracking columns

Revision ID: 1355e897775e
Revises: 773030f215d5
Create Date: 2023-06-24 10:40:19.186046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1355e897775e'
down_revision = '773030f215d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shippedsample', sa.Column('result_notified', sa.Boolean(), nullable=True))
    op.add_column('shippedsample', sa.Column('ext_sample_uid', sa.String(), nullable=True))
    op.add_column('shippedsample', sa.Column('ext_sample_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shippedsample', 'ext_sample_id')
    op.drop_column('shippedsample', 'ext_sample_uid')
    op.drop_column('shippedsample', 'result_notified')
    # ### end Alembic commands ###
