"""changed bill_id to unique

Revision ID: 96362c3c647e
Revises: 528edd1cff8b
Create Date: 2025-04-27 10:17:17.735490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96362c3c647e'
down_revision = '528edd1cff8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_test_bill_bill_id'), 'test_bill', ['bill_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_bill_bill_id'), table_name='test_bill')
    # ### end Alembic commands ###
