"""add-grind-documents-minors

Revision ID: 23f0aedb34c8
Revises: 5250318822af
Create Date: 2025-02-27 12:34:29.410620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f0aedb34c8'
down_revision = '5250318822af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ai_authoring_session', sa.Column('ai_model_uid', sa.String(), nullable=True))
    op.drop_constraint('document_ai_authoring_session_model_uid_fkey', 'document_ai_authoring_session', type_='foreignkey')
    op.create_foreign_key(None, 'document_ai_authoring_session', 'document_ai_model', ['ai_model_uid'], ['uid'])
    op.drop_column('document_ai_authoring_session', 'model_uid')
    op.add_column('document_ai_review_feedback', sa.Column('ai_model_uid', sa.String(), nullable=True))
    op.drop_constraint('document_ai_review_feedback_model_uid_fkey', 'document_ai_review_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'document_ai_review_feedback', 'document_ai_model', ['ai_model_uid'], ['uid'])
    op.drop_column('document_ai_review_feedback', 'model_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_ai_review_feedback', sa.Column('model_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_ai_review_feedback', type_='foreignkey')
    op.create_foreign_key('document_ai_review_feedback_model_uid_fkey', 'document_ai_review_feedback', 'document_ai_model', ['model_uid'], ['uid'])
    op.drop_column('document_ai_review_feedback', 'ai_model_uid')
    op.add_column('document_ai_authoring_session', sa.Column('model_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_ai_authoring_session', type_='foreignkey')
    op.create_foreign_key('document_ai_authoring_session_model_uid_fkey', 'document_ai_authoring_session', 'document_ai_model', ['model_uid'], ['uid'])
    op.drop_column('document_ai_authoring_session', 'ai_model_uid')
    # ### end Alembic commands ###
