"""add doc humbnail

Revision ID: 26f8e5d1c474
Revises: 2c0d01dc1021
Create Date: 2025-03-08 22:04:37.977363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f8e5d1c474'
down_revision = '2c0d01dc1021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_version', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_version', 'thumbnail')
    # ### end Alembic commands ###
