"""removed-auditlog

Revision ID: 28042fd2e903
Revises: e598ed62784d
Create Date: 2024-08-02 17:30:19.725564

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '28042fd2e903'
down_revision = 'e598ed62784d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_uid', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
                    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
                    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('action', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('state_before', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('state_after', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('uid', name='audit_log_pkey')
                    )
    op.create_index('ix_audit_log_uid', 'audit_log', ['uid'], unique=False)
    # ### end Alembic commands ###
