"""editor_tracking

Revision ID: 2c0d01dc1021
Revises: a9d53f4225ae
Create Date: 2025-03-08 09:57:53.660514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0d01dc1021'
down_revision = 'a9d53f4225ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_version', sa.Column('editor', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_version', 'editor')
    # ### end Alembic commands ###
