"""minor changes

Revision ID: 3f4a5704d9c2
Revises: 247906fc37e3
Create Date: 2023-12-30 10:39:34.504608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4a5704d9c2'
down_revision = '247906fc37e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_order', sa.Column('fulfilled_by_uid', sa.String(), nullable=True))
    op.drop_constraint('stock_order_fullfilled_by_uid_fkey', 'stock_order', type_='foreignkey')
    op.create_foreign_key(None, 'stock_order', 'user', ['fulfilled_by_uid'], ['uid'])
    op.drop_column('stock_order', 'fullfilled_by_uid')
    op.alter_column('stock_order_product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_order_product', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('stock_order', sa.Column('fullfilled_by_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_order', type_='foreignkey')
    op.create_foreign_key('stock_order_fullfilled_by_uid_fkey', 'stock_order', 'user', ['fullfilled_by_uid'], ['uid'])
    op.drop_column('stock_order', 'fulfilled_by_uid')
    # ### end Alembic commands ###
