"""added stock transaction custodian

Revision ID: 56c47ebb220c
Revises: aa39af866443
Create Date: 2023-07-16 14:43:21.205818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c47ebb220c'
down_revision = 'aa39af866443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocktransaction', sa.Column('issued_to_uid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'stocktransaction', 'user', ['issued_to_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocktransaction', type_='foreignkey')
    op.drop_column('stocktransaction', 'issued_to_uid')
    # ### end Alembic commands ###
