"""updated sequencer

Revision ID: 6433ae34d650
Revises: 86734b6962eb
Create Date: 2023-04-16 17:57:12.424429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6433ae34d650'
down_revision = '86734b6962eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idsequence', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idsequence', 'updated')
    # ### end Alembic commands ###
