"""client auditable

Revision ID: 86734b6962eb
Revises: ccddc0ed7ee1
Create Date: 2023-04-16 10:15:34.322087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86734b6962eb'
down_revision = 'ccddc0ed7ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
