"""add-abx-lab_selection

Revision ID: 8e6eacca94cf
Revises: b62be2f0ddfb
Create Date: 2025-02-21 16:07:44.765533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6eacca94cf'
down_revision = 'b62be2f0ddfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abx_laboratory_antibiotic',
    sa.Column('laboratory_uid', sa.String(), nullable=False),
    sa.Column('antibiotic_uid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['antibiotic_uid'], ['abx_antibiotic.uid'], ),
    sa.ForeignKeyConstraint(['laboratory_uid'], ['laboratory.uid'], ),
    sa.PrimaryKeyConstraint('laboratory_uid', 'antibiotic_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abx_laboratory_antibiotic')
    # ### end Alembic commands ###
