"""add-comments

Revision ID: a7a3133490f4
Revises: 5a6836fd5dd0
Create Date: 2025-03-01 16:39:11.935950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a3133490f4'
down_revision = '5a6836fd5dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grind_errand_discussion',
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('errand_uid', sa.String(), nullable=True),
    sa.Column('parent_uid', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_uid', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_uid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uid'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['errand_uid'], ['grind_errand.uid'], ),
    sa.ForeignKeyConstraint(['parent_uid'], ['grind_errand_discussion.uid'], ),
    sa.ForeignKeyConstraint(['updated_by_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_grind_errand_discussion_uid'), 'grind_errand_discussion', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grind_errand_discussion_uid'), table_name='grind_errand_discussion')
    op.drop_table('grind_errand_discussion')
    # ### end Alembic commands ###
