"""added reffral verified by name and submitted by name

Revision ID: aa39af866443
Revises: 1355e897775e
Create Date: 2023-07-16 08:20:42.884710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa39af866443'
down_revision = '1355e897775e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysisresult', sa.Column('submitted_by_name', sa.String(), nullable=True))
    op.add_column('analysisresult', sa.Column('verified_by_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysisresult', 'verified_by_name')
    op.drop_column('analysisresult', 'submitted_by_name')
    # ### end Alembic commands ###
