"""its me

Revision ID: ccddc0ed7ee1
Revises: 1ef66812cd10
Create Date: 2023-04-10 01:59:09.340001

"""


# revision identifiers, used by Alembic.
revision = "ccddc0ed7ee1"
down_revision = "1ef66812cd10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
