"""made chges

Revision ID: f79adc6dd35a
Revises: 948a829e0626
Create Date: 2023-12-09 14:55:05.028271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79adc6dd35a'
down_revision = '948a829e0626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('analysis_discount_voucher_code_uid_fkey', 'analysis_discount', type_='foreignkey')
    op.drop_column('analysis_discount', 'voucher_code_uid')
    op.add_column('laboratory_setting', sa.Column('allow_auto_billing', sa.Boolean(), nullable=True))
    op.add_column('profile_discount', sa.Column('profile_uid', sa.String(), nullable=True))
    op.drop_constraint('profile_discount_voucher_code_uid_fkey', 'profile_discount', type_='foreignkey')
    op.drop_constraint('profile_discount_analysis_profile_uid_fkey', 'profile_discount', type_='foreignkey')
    op.create_foreign_key(None, 'profile_discount', 'profile', ['profile_uid'], ['uid'])
    op.drop_column('profile_discount', 'voucher_code_uid')
    op.drop_column('profile_discount', 'analysis_profile_uid')
    op.add_column('test_bill', sa.Column('total_paid', sa.Float(), nullable=False))
    op.add_column('voucher', sa.Column('used', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'voucher', ['name'])
    op.drop_column('voucher', 'only_for_staff')
    op.drop_column('voucher', 'single_use')
    op.add_column('voucher_code', sa.Column('voucher_uid', sa.String(), nullable=False))
    op.add_column('voucher_code', sa.Column('usage_limit', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'voucher_code', ['code'])
    op.create_foreign_key(None, 'voucher_code', 'voucher', ['voucher_uid'], ['uid'])
    op.alter_column('voucher_customer', 'patient_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('voucher_customer', 'voucher_code_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voucher_customer', 'voucher_code_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('voucher_customer', 'patient_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'voucher_code', type_='foreignkey')
    op.drop_constraint(None, 'voucher_code', type_='unique')
    op.drop_column('voucher_code', 'usage_limit')
    op.drop_column('voucher_code', 'voucher_uid')
    op.add_column('voucher', sa.Column('single_use', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('voucher', sa.Column('only_for_staff', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voucher', type_='unique')
    op.drop_column('voucher', 'used')
    op.drop_column('test_bill', 'total_paid')
    op.add_column('profile_discount', sa.Column('analysis_profile_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('profile_discount', sa.Column('voucher_code_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profile_discount', type_='foreignkey')
    op.create_foreign_key('profile_discount_analysis_profile_uid_fkey', 'profile_discount', 'profile', ['analysis_profile_uid'], ['uid'])
    op.create_foreign_key('profile_discount_voucher_code_uid_fkey', 'profile_discount', 'voucher_code', ['voucher_code_uid'], ['uid'])
    op.drop_column('profile_discount', 'profile_uid')
    op.drop_column('laboratory_setting', 'allow_auto_billing')
    op.add_column('analysis_discount', sa.Column('voucher_code_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('analysis_discount_voucher_code_uid_fkey', 'analysis_discount', 'voucher_code', ['voucher_code_uid'], ['uid'])
    # ### end Alembic commands ###
